### ISSUE TITLE
Failed to train model Gp1

### ISSUE THREAD

**Issue by AuraKing** [WendongMao/Intelligent_Typography#1]
Hi! I tried to retrain Gp1. Why do I get black and white results?

**Comment by WendongMao** [comment]
Thanks for your attention to our work .&nbsp; The results of GP1 should be the prototype of stylized text. Could you give me more details about your results？


&nbsp;Wendong Mao
Assistant Professor
Sun Yat-Sen University

--------------原始邮件--------------
发件人："AuraKing ***@***.***&gt;;
发送时间：2024年3月22日(星期五) 凌晨4:28
收件人："WendongMao/Intelligent_Typography" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[WendongMao/Intelligent_Typography] Failed to train model Gp1 (Issue #1)
-----------------------------------

 

 
Hi! I tried to retrain Gp1. Why do I get black and white results?

**Comment by AuraKing** [comment]
> 感谢您对我们工作的关注。 GP1的结果应该是风格化文本的雏形。您能详细介绍一下您的研究结果吗？  毛文东 助理教授 中山大学
> [……](#)
> --------------原始邮件-------------- 发件人："AuraKing ***@***.***>;发送时间：2024年3月22日（星期五）凌晨4:28 食谱：“WendongMao/Intelligent_Typography”***@***.***>；抄送：“订阅了***@** *.***>; 主题：[WendongMao/Intelligent_Typography] 训练模型 Gp1 失败（问题#1）-------------------------------- - 你好！我尝试重新训练 Gp1。为什么我得到黑白结果？— 直接回复此电子邮件、在 GitHub 上查看或取消订阅。您收到此消息是因为您订阅了该主题。消息 ID：***@***.***>

Thank you very much for your prompt answer.
<img width="682" alt="截屏2024-03-22 13 14 41" src="https://github.com/WendongMao/Intelligent_Typography/assets/46162008/504019a6-ee41-4644-a978-c57f102e40c5">
 The code works fine, but the training results are shown below.

**Comment by WendongMao** [comment]
Training GP1 should use the original style image. It is note that only one image is used to train GP1. Can you provide the  style image  you used?

**Comment by AuraKing** [comment]
> Training GP1 should use the original style image. It is note that only one image is used to train GP1. Can you provide the style image you used?

After checking, I found that it was really because I used the wrong picture to train Gp1. Thanks again for your answer!
